### ISSUE TITLE
Send appropriate email notifications on events

### ISSUE THREAD

**Issue by shgysk8zer0** [KVSun/kvsun.com#162]
Will need to discuss needs. This only serves as a placeholder and means of opening the discussion.
I can take some guesses, but would rather ask about this. Some things are obvious but still leave room for discussion on what information needs to be sent to whom and when.

- [x] New online subscription
- [x] Comment posted
- [x] Various form submissions (obits, letter to the editor, etc.)
@pudljumpr47 @KVSun/kv-sun-employees

**Comment by pudljumpr47** [comment]
Here is the new subcription pricing. as for who will be responsible for 
these things below I would say the same department that did them when we 
were with Town News.

Thanks,

Marsha
