### ISSUE TITLE
Add login checks

### ISSUE THREAD

**Issue by shgysk8zer0** [KVSun/kvsun.com#25]
Add login check to page loading/response handling. Could extend this to check subscription status.

Each page and handler will need to check this.

**Comment by kvsun-editor** [comment]
-  Will use [`shgysk8zer0\Login`](https://github.com/shgysk8zer0/login) for this
- Need to be able to set cookie/session using symmetrically encrypted `shgyk8zer0\Login\User`
- Restructure database tables
- Make Login class (tables) extensible
- Need to handle encryption to set cookies & session (do not want this to be something that user can alter)
- Don't forget to set expiration in cookie data
